// @ts-nocheck
'use client'
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5CbmLe0W0l6
 */

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import SkillEditDialog from '@/components/skill-edit-dialog';
import { SortableItem } from './SortableItem';

export function SkillsSection({ resume, setResume, isDragging }) {
  const allToolsAndFrameworks = ['React', 'Node.js', 'Next.js', 'Vue', 'Angular', 'Django', 'ojw', 'wfoj', 'jfwo'];
  const allProgrammingLanguages = ['Java', 'C', 'C++', 'Python', 'JavaScript', 'TypeScript'];

  const updateSkills = (category, updatedSkills) => {
    setResume(prevResume => ({
      ...prevResume,
      skills: {
        ...prevResume.skills,
        [category]: updatedSkills,
      },
    }));
  };

  return (
      <div className="space-y-4">
        <SkillEditDialog
          title="Tools and Frameworks"
          skills={resume.skills.toolsAndFrameworks || []}
          allSkills={allToolsAndFrameworks}
          setSkills={(updatedSkills) => updateSkills('toolsAndFrameworks', updatedSkills)}
          dialogButtonText="Add new Tool/Framework"
        />
        <Separator />
        <SkillEditDialog
          title="Programming Languages"
          skills={resume.skills.programmingLanguages || []}
          allSkills={allProgrammingLanguages}
          setSkills={(updatedSkills) => updateSkills('programmingLanguages', updatedSkills)}
          dialogButtonText="Add New Language"
        />
      </div>
  );
}

export default SkillsSection;
